version: '3'
services:

  db:
    image: mysql:8.3
    container_name: items_db
    restart: unless-stopped
    tty: true
    ports:
      - "23306:3306"
    environment:
      MYSQL_DATABASE: items_db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  cache:
    image: redis:7.2
    container_name: cache
    restart: unless-stopped
    tty: true
    ports:
      - "6379:6379"

