version: '3'
services:

  db:
    image: mysql:8.3
    container_name: items_db_test
    restart: unless-stopped
    tty: true
    ports:
      - "23306:3306"
    environment:
      MYSQL_DATABASE: items_db_test
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

